'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {plan,createBulkPublisher}=require('../src/bulk-publish');
function fixture(){return {id:'p',siteUrl:'https://example.com',profile:{revision:1,status:'confirmed'},deployment:{repositoryPath:'test'},workflows:[1,2].map(n=>({id:String(n),title:'Page '+n,action:'UPDATE_EXISTING',targetPath:'/page'+n,status:'AWAITING_APPROVAL',briefHash:'h'+n,profileRevision:1,events:[],brief:{changes:[{id:'title',area:'Title',proposed:'New title '+n},{id:'sections',area:'Sections',proposed:'Pending'}]}}))};}
function setup(overrides={}){let p=fixture();const calls=[];const store={getPrivateProject:()=>structuredClone(p),listProjects:()=>[{id:p.id}],updateProject:(id,update)=>{p={...p,...structuredClone(update)};}};const dep={preparePreview:async w=>{calls.push('prepare'+w.id);return {prepared:true,revision:'abc',worktreePath:'test',sourceFile:'page.html'};},publishPreview:async w=>{calls.push('publish'+w.id);return {url:'https://example.com'+w.targetPath};},...overrides};return {manager:createBulkPublisher(store,dep),store,calls,get p(){return p;}};}
async function done(manager){while(manager.isBusy())await new Promise(resolve=>setImmediate(resolve));}
test('bulk review excludes unsafe types, duplicates and language blockers',()=>{const p=fixture();p.workflows.push({...p.workflows[0],id:'3'},{...p.workflows[0],id:'4',action:'CTR_TEST'},{...p.workflows[1],id:'5',blockedReason:'Unknown language'});const r=plan(p);assert.equal(r.items.length,2);assert.equal(r.skipped.length,2);assert.equal(r.notReady.length,1);assert.equal(r.items[0].changes.length,1);assert.equal(r.items[0].pending.length,1);});
test('discovered holds are reported as unfinished records, not excluded recommendations',()=>{const p=fixture();p.workflows.push({...p.workflows[0],id:'hold',status:'DISCOVERED',action:'HOLD',brief:{changes:[]}});const r=plan(p);assert.equal(r.items.length,2);assert.equal(r.skipped.length,0);assert.equal(r.notReady.length,1);assert.match(r.notReady[0].reason,/taslağı/);});
test('obsolete blocked history is not presented as a recommendation needing user action',()=>{const p=fixture();p.workflows.push({...p.workflows[0],id:'old',blockedReason:'Bu görev güncel analizde yer almıyor.'});const r=plan(p);assert.equal(r.skipped.length,0);assert.equal(r.notReady.length,1);assert.match(r.notReady[0].reason,/güncel analiz/);});
test('bulk requires explicit snapshot confirmation and runs sequentially with review URLs',async()=>{const f=setup();const r=plan(f.p);assert.throws(()=>f.manager.start('p',{token:r.token}));assert.throws(()=>f.manager.start('p',{token:'stale',confirmation:'PUBLISH_REVIEWED_CHANGES'}));assert.deepEqual(f.calls,[]);f.manager.start('p',{token:r.token,confirmation:'PUBLISH_REVIEWED_CHANGES'});assert.throws(()=>f.manager.start('p',{token:r.token,confirmation:'PUBLISH_REVIEWED_CHANGES'}));await done(f.manager);assert.deepEqual(f.calls,['prepare1','publish1','prepare2','publish2']);assert.equal(f.p.bulkPublish.status,'completed');assert.ok(f.p.bulkPublish.items.every(i=>i.status==='published'&&i.url));assert.ok(f.p.workflows.every(w=>w.status==='MONITORING'&&w.monitoringBaseline));});
test('failure stops remaining queue and preserves previously published results',async()=>{let count=0;const f=setup({publishPreview:async w=>{if(++count===2)throw Error('Hosting failure');return {url:'https://example.com'+w.targetPath};}});f.manager.start('p',{token:plan(f.p).token,confirmation:'PUBLISH_REVIEWED_CHANGES'});await done(f.manager);assert.equal(f.p.bulkPublish.status,'failed');assert.equal(f.p.bulkPublish.items[0].status,'published');assert.equal(f.p.workflows[1].status,'FAILED');assert.equal(f.p.bulkPublish.items[0].url,'https://example.com/page1');});
test('restart never replays a possibly completed live publish',()=>{const f=setup();f.store.updateProject('p',{bulkPublish:{status:'running',items:[{id:'1',status:'publishing'}]},workflows:[{...f.p.workflows[0],status:'PUBLISHING',execution:{state:'publishing'}}]});f.manager.recover();assert.equal(f.p.bulkPublish.status,'interrupted');assert.equal(f.p.workflows[0].status,'FAILED');assert.deepEqual(f.calls,[]);});
test('first preparation error leaves remaining items unexecuted',async()=>{let calls=0;const f=setup({preparePreview:async()=>{calls++;throw Error('Build failed');}});f.manager.start('p',{token:plan(f.p).token,confirmation:'PUBLISH_REVIEWED_CHANGES'});await done(f.manager);assert.equal(calls,1);assert.equal(f.p.bulkPublish.items[1].status,'queued');assert.equal(f.p.workflows[1].status,'AWAITING_APPROVAL');});
test('editing a proposed value invalidates the reviewed token',()=>{const f=setup();const review=plan(f.p);f.p.workflows[0].brief.changes[0].proposed='Changed';assert.throws(()=>f.manager.start('p',{token:review.token,confirmation:'PUBLISH_REVIEWED_CHANGES'}));assert.deepEqual(f.calls,[]);});
